version: '2'

services:
    orientdb:
        image: orientdb:2.2.13
        container_name: smevente.orientdb
        environment:
            ORIENTDB_ROOT_PASSWORD: root
        ports:
            - "2424:2424"
            - "2480:2490"
        volumes:
            - ../../../databases:/orientdb/databases
            - ../../.volumes/log/orientdb:/orientdb/log
    postfix:
        image: veny/postfix
        container_name: smevente.postfix
        ports:
            - "25:25"
        volumes:
            - ../../.volumes/log/postfix:/var/log
